# Generated by Django 3.2.5 on 2021-07-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='time',
            field=models.TimeField(verbose_name='Время сообщения'),
        ),
    ]
